import { useEffect, useRef } from 'react';
import { Header } from './components/layout/Header';
import { Footer } from './components/layout/Footer';
import { Layout } from './components/layout/Layout';
import { InputForm } from './components/inputs/InputForm';
import { ResultTable } from './components/results/ResultTable';
import { ChartPlaceholder } from './components/results/ChartPlaceholder';
import { ExportBar } from './components/export/ExportBar';
import { WACCSummaryLine } from './components/results/WACCSummaryLine';
import { WACCRangeBar } from './components/results/WACCRangeBar';
import { AnalysisSection } from './components/results/AnalysisSection';
import { ToastStack, useToasts } from './components/Toast';
import { useWaccForm } from './hooks/useWaccForm';
import { useWaccResult } from './hooks/useWaccResult';

export function App() {
  const {
    inputs,
    updateShared,
    updateBound,
    copyBound,
    reset,
    errors,
    isValid,
    initialSource,
  } = useWaccForm();
  const { result, loading, error } = useWaccResult(inputs, isValid);
  const toasts = useToasts();
  const welcomedRef = useRef(false);

  // Inform the user once at mount if we restored from a shared URL. Fires after first render
  // so the toast doesn't compete with initial paint.
  useEffect(() => {
    if (welcomedRef.current) return;
    welcomedRef.current = true;
    if (initialSource === 'hash') toasts.push('Loaded shared calculation from URL.', 'success');
  }, [initialSource]); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div className="flex h-full flex-col">
      <div className="header-bar">
        <Header companyName={inputs.companyName} valuationDate={inputs.valuationDate} />
      </div>
      <div className="print-header px-6 py-3">
        <h1 className="text-lg font-semibold">
          WACC Analysis — {inputs.companyName || 'Company'}
        </h1>
        <p className="text-sm text-slate-600">
          As at {inputs.valuationDate} · Currency: {inputs.currency} · Generated by WACC Calculator
        </p>
      </div>
      <Layout
        left={
          <div className="input-panel">
            <InputForm
              inputs={inputs}
              updateShared={updateShared}
              updateBound={updateBound}
              copyBound={copyBound}
              errors={errors}
            />
          </div>
        }
        right={
          <div className="result-panel flex flex-col gap-4">
            {error && (
              <div className="rounded border border-amber-300 bg-amber-50 px-3 py-2 text-xs text-amber-800">
                Live data temporarily unavailable — showing last successful calculation.{' '}
                <span className="text-stone">{error}</span>
              </div>
            )}
            <div className={`result-table transition-opacity ${loading && result ? 'opacity-70' : ''}`}>
              <ResultTable result={result} />
            </div>
            {result && (
              <div className="wacc-summary-line">
                <WACCSummaryLine result={result} />
              </div>
            )}
            {result && (
              <div className="wacc-range-bar">
                <WACCRangeBar result={result} />
              </div>
            )}
            {result ? <AnalysisSection result={result} /> : <ChartPlaceholder />}
            <ExportBar
              result={result}
              inputs={inputs}
              onReset={reset}
              onShareNotice={(text, kind) => toasts.push(text, kind)}
            />
          </div>
        }
      />
      <Footer />
      <ToastStack messages={toasts.messages} onDismiss={toasts.dismiss} />
    </div>
  );
}
