import { Header } from './components/layout/Header';
import { Layout } from './components/layout/Layout';
import { InputForm } from './components/inputs/InputForm';
import { ResultTable } from './components/results/ResultTable';
import { ChartPlaceholder } from './components/results/ChartPlaceholder';
import { ExportBar } from './components/export/ExportBar';
import { WACCSummaryLine } from './components/results/WACCSummaryLine';
import { WACCRangeBar } from './components/results/WACCRangeBar';
import { AnalysisSection } from './components/results/AnalysisSection';
import { useWaccForm } from './hooks/useWaccForm';
import { useWaccResult } from './hooks/useWaccResult';

export function App() {
  const { inputs, updateShared, updateBound, copyBound, errors, isValid } = useWaccForm();
  const { result, loading, error, calculate } = useWaccResult();

  return (
    <div className="flex h-full flex-col">
      <div className="header-bar">
        <Header companyName={inputs.companyName} valuationDate={inputs.valuationDate} />
      </div>
      <div className="print-header px-6 py-3">
        <h1 className="text-lg font-semibold">
          WACC Analysis — {inputs.companyName || 'Company'}
        </h1>
        <p className="text-sm text-slate-600">
          As at {inputs.valuationDate} · Currency: {inputs.currency} · Generated by WACC Calculator
        </p>
      </div>
      <Layout
        left={
          <div className="input-panel">
            <InputForm
              inputs={inputs}
              updateShared={updateShared}
              updateBound={updateBound}
              copyBound={copyBound}
              errors={errors}
              isValid={isValid}
              loading={loading}
              onCalculate={() => calculate(inputs)}
            />
          </div>
        }
        right={
          <div className="result-panel flex flex-col gap-4">
            {error && (
              <div className="rounded border border-amber-300 bg-amber-50 px-3 py-2 text-xs text-amber-800">
                {error}
              </div>
            )}
            <div className="result-table">
              <ResultTable result={result} />
            </div>
            {result && <WACCSummaryLine result={result} />}
            {result && <WACCRangeBar result={result} />}
            {result ? <AnalysisSection result={result} /> : <ChartPlaceholder />}
            <ExportBar result={result} inputs={inputs} />
          </div>
        }
      />
    </div>
  );
}
